import type {PilotRun} from '@/lib/pilot-model';

export type View = 'inicio'|'descobrir'|'criar'|'virais'|'galeria'|'calendario'|'automacoes'|'marca'|'contas'|'resultados'|'uso'|'configuracoes'|'ajuda'|'editor';
export type Format = 'meme'|'educativo'|'amiga';
export const formatNames:Record<Format,string>={meme:'Meme',educativo:'Educativo',amiga:'Conversa de amiga'};
export const photos=['01-celular-cafe-cama.jpg','02-quarto-celular.jpg','03-cafe-rotina.jpg','04-celular-lencois.jpg','05-maos-celular-laranja.jpg'].map(x=>`/workspace/${x}`);
export type Slide={id:string;image:string;text:string;position:'top'|'center'|'bottom';size:number};
export type Content={id:string;title:string;format:Format;caption:string;slides:Slide[];video?:string;poster?:string;origin:'example'|'pilot'|'local';status:'draft'|'saved'|'discarded';createdAt:string;sourceId?:string;reference?:string};
export type Media={id:string;name:string;src:string;kind:'image'|'video';collection:string;origin:string};
export type Plan={id:string;contentId:string;platform:'TikTok'|'Instagram';date:string;time:string;timezone:string;note:string};
export type Campaign={id:string;name:string;objective:string;formats:Format[];days:number[];perDay:number;weeks:number;start:string;platform:'TikTok'|'Instagram';source:'mix'|'own'|'pinterest';status:'draft'|'paused'};
export type Brand={name:string;site:string;description:string;audience:string;problem:string;benefit:string;tone:string;angles:string[];avoid:string;mention:string;color:string;logo:string};
export type WorkspaceData={version:1;brand:Brand;brandEdited?:boolean;contents:Content[];media:Media[];plans:Plan[];campaigns:Campaign[];favorites:string[];collections:string[];preferences:{language:string;timezone:string;readyAlerts:boolean;failureAlerts:boolean;weeklyAlerts:boolean}};
export function uid(){return crypto.randomUUID()}
export function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
export function freshSlides(format:Format):Slide[]{return Array.from({length:format==='meme'?1:5},(_,i)=>({id:uid(),image:photos[i%photos.length],text:'',position:i===0?'top':'center',size:30}))}
export function fromPilot(run:PilotRun):Content[]{return run.pieces.map(p=>({id:`pilot:${p.id}`,sourceId:p.id,title:p.hook,format:p.format.toLowerCase().includes('meme')?'meme':/amiga|story/i.test(p.format)?'amiga':'educativo',caption:p.caption,slides:p.assets.filter(a=>a.kind==='image').map((a,i)=>({id:`${p.id}:${i}`,image:a.url,text:'',position:'center',size:30})),video:p.assets.find(a=>a.kind==='video')?.url,poster:p.assets.find(a=>a.kind==='video')?.poster,origin:'pilot',status:p.status==='approved'?'saved':p.status==='rejected'?'discarded':'draft',createdAt:run.createdAt}))}
export function initialData(run?:PilotRun|null):WorkspaceData{
 const demoTitles=['Antes de olhar um perfil, eu faria isso','Amiga, um print sozinho não conta tudo','Quando você tenta lembrar o que mudou','3 coisas para observar com mais contexto','Você não precisa conferir tudo de novo','Uma forma mais leve de acompanhar'];
 const contents:Content[]=run?[]:demoTitles.map((title,i)=>({id:`example-${i}`,title,format:i===2?'meme':i%2?'amiga':'educativo',caption:'Uma referência preparada para explorar a experiência da Launchwing. Revise e adapte antes de usar.',slides:[{id:`sample-${i}`,image:photos[i%photos.length],text:title,position:i%2?'center':'top',size:30},...photos.slice(1,4).map((p,j)=>({id:`sample-${i}-${j}`,image:p,text:['Comece pelo que você quer entender.','Olhe a sequência, não só um momento.','Guarde o contexto para comparar depois.'][j],position:'center' as const,size:28}))],...(i===2?{video:'/pilot/insta-radar/v2-casual/insta-radar-meme.mp4',poster:'/pilot/insta-radar/v2-casual/capa.jpg'}:{}),origin:'example',status:i<3?'draft':'saved',createdAt:'2026-09-12T00:00:00Z'}));
 return {version:1,brand:{name:run?(run.context.name||run.onboarding?.answers.company||'Sua marca'):'Insta Radar',site:run?.url||'https://insta-radar-two.vercel.app/',description:run?run.context.description:'Acompanhamento de perfis do Instagram, com histórico para comparar mudanças ao longo do tempo.',audience:run?run.context.audience:'Pessoas que querem acompanhar perfis e organizar suas observações.',problem:run?run.context.situations:'Conferir tudo manualmente e perder o contexto entre uma visita e outra.',benefit:run?'':'Organizar o histórico e facilitar a comparação.',tone:'Próxima, simples e útil. Como uma amiga ajudando.',angles:run?[]:['Mais contexto, menos achismo','Pequenos hábitos que economizam tempo','O que observar antes de concluir'],avoid:run?'':'Promessas de certeza, invasão de privacidade e linguagem alarmista.',mention:'Às vezes',color:'#2547FF',logo:''},contents,media:photos.map((src,i)=>({id:`photo-${i}`,name:['Celular e café','Um momento em casa','Café da manhã','Celular sobre lençóis','Rotina no celular'][i],src,kind:'image',collection:'Rotina e tecnologia',origin:'Pinterest · exemplo aprovado'})),plans:[],campaigns:[],favorites:[],collections:['Rotina e tecnologia'],preferences:{language:'Português (Brasil)',timezone:'America/Sao_Paulo',readyAlerts:true,failureAlerts:true,weeklyAlerts:false}};
}

const DB='launchwing-frontend-v1';
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('workspaces');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function readWorkspace(key:string):Promise<WorkspaceData|null>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('workspaces','readonly');const req=tx.objectStore('workspaces').get(key);req.onsuccess=()=>resolve(req.result?.version===1?req.result:null);req.onerror=()=>reject(req.error);tx.oncomplete=()=>db.close()})}
export async function clearWorkspace(key:string):Promise<void>{const db=await database();return new Promise((resolve,reject)=>{const tx=db.transaction('workspaces','readwrite');tx.objectStore('workspaces').delete(key);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=tx.onabort=()=>{db.close();reject(tx.error)}})}
