"use client";
import type {ReactNode} from "react";
import {FolderOpen,Clock3,Clapperboard,Layers3} from "lucide-react";
import {Button} from "@/components/ui/button";
import {formatNames,type Content} from "./model";
export function Action({children,onClick,secondary=false,disabled=false,type='button'}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;disabled?:boolean;type?:'button'|'submit'}){return <Button type={type} onClick={onClick} disabled={disabled} variant={secondary?'outline':'default'} className={`fw-button ${secondary?'secondary':''}`}>{children}</Button>}
export function PageHeading({title,description,action,eyebrow}:{title:string;description?:string;action?:ReactNode;eyebrow?:string}){return <div className="fw-page-heading"><div>{eyebrow&&<span className="fw-eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function EmptyState({icon:Icon=FolderOpen,title,description,action}:{icon?:typeof FolderOpen;title:string;description:string;action?:ReactNode}){return <div className="fw-empty"><span><Icon size={26}/></span><h2>{title}</h2><p>{description}</p>{action}</div>}
export function LocalNote({children}:{children?:ReactNode}){return <p className="fw-local-note"><Clock3 size={15}/>{children||'Rascunhos salvos na sua conta. A publicação nas redes será conectada na próxima etapa.'}</p>}
export function PostPreview({item,index=0,compact=false}:{item:Content;index?:number;compact?:boolean}){const slide=item.slides[index]||item.slides[0];const textSize=slide?Math.min(slide.size,Math.sqrt(132000/Math.max(1,slide.text.length))):30;return <div className={`fw-post-preview ${compact?'compact':''}`}>{item.video?<video src={item.video} poster={item.poster} muted playsInline controls={!compact} preload="metadata"/>:slide?<><img src={slide.image} alt={slide.text||item.title}/>{slide.text&&<div className={`fw-sticker ${slide.position}`} style={{fontSize:`${textSize/3.65}cqw`}}><span>{slide.text}</span></div>}</>:<div className="fw-post-blank"><Clapperboard size={36}/></div>}{compact&&<span className="fw-format-tag">{item.video?<Clapperboard size={13}/>:<Layers3 size={13}/>} {formatNames[item.format]}</span>}</div>}
export function ContentCard({item,onClick,extra}:{item:Content;onClick:()=>void;extra?:ReactNode}){return <article className="fw-content-card"><button className="fw-card-open" onClick={onClick} aria-label={`Abrir ${item.title}`}><PostPreview item={item} compact/></button><div className="fw-card-copy"><span className={`fw-status ${item.status}`}>{item.postagem??(item.status==='saved'?'Salvo':item.status==='discarded'?'Descartado':'Para revisar')}</span><h3><button onClick={onClick}>{item.title}</button></h3><div className="fw-card-meta"><span>{item.origin==='example'?'Exemplo preparado':item.origin==='pilot'?'Do seu produto':'Rascunho local'}</span>{extra}</div></div></article>}
