"use client";
import {useState, type FormEvent} from 'react';
import {ArrowUpRight, ArrowRight, Check, Plus, ChevronLeft, ChevronRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Accordion, AccordionItem, AccordionTrigger, AccordionContent} from '@/components/ui/accordion';

const examples=[
 {type:'Apresentação',title:'Você criou. Agora mostre.',copy:'Seu produto já existe. O próximo passo é colocar a ideia na frente de quem precisa dela.',caption:'Construir foi só o começo. A Launchwing está preparando um jeito de transformar o link do seu produto em conteúdo para o Instagram. Conheça a proposta e entre na lista de acesso antecipado.',tone:'blue'},
 {type:'Problema',title:'Seu produto não pode ser um segredo.',copy:'Uma boa ideia também precisa aparecer. Explicar o que ela resolve é um começo.',caption:'Quem precisa do seu produto talvez ainda não saiba que ele existe. Comece pela dor que você resolve — e torne essa mensagem fácil de encontrar.',tone:'paper'},
 {type:'Funcionamento',title:'Do link ao próximo post.',copy:'Link do produto. Conteúdo criado. Revisão. Publicação.',caption:'Esse é o fluxo que estamos construindo na Launchwing: sete carrosséis a partir do seu produto, com revisão antes de agendar no Instagram. Quer acompanhar a abertura? Entre na lista.',tone:'citron'},
 {type:'Objeção',title:'Sua voz continua sendo sua.',copy:'O conteúdo chega pronto para revisar. A palavra final continua com você.',caption:'Automatizar a criação não precisa significar perder o controle. Na proposta da Launchwing, você revisa o conteúdo e aprova o que vai para o ar.',tone:'ink'},
 {type:'Benefício',title:'Mais espaço para construir.',copy:'Uma rotina de conteúdo que cabe na vida de quem cuida do produto.',caption:'Ideia, texto, design, legenda, agendamento. Estamos reunindo essas etapas para que divulgar seu produto deixe de começar do zero toda semana.',tone:'blue'},
 {type:'Bastidores',title:'Estamos preparando a decolagem.',copy:'Um produto para ajudar outros produtos a aparecer.',caption:'A Launchwing está em preparação. Nosso primeiro foco é transformar um link em sete carrosséis com legenda, revisão e agendamento no Instagram.',tone:'paper'},
 {type:'Convite',title:'Seu próximo passo é aparecer.',copy:'Conheça a Launchwing. Entre na lista de acesso antecipado.',caption:'Criou um SaaS, microsaas ou infoapp? Estamos construindo a Launchwing para ajudar com sua rotina de conteúdo. Cadastre seu e-mail para receber o aviso de abertura.',tone:'citron'},
];
const faqs=[
 ['A Launchwing já está disponível?','Ainda não. Estamos preparando a primeira versão. A lista de acesso antecipado registra seu interesse para receber um aviso quando o acesso abrir. Ainda não há uma data definida.'],
 ['O que a primeira versão vai fazer?','O fluxo planejado começa com o link do seu produto e entrega sete carrosséis com legenda e chamada para ação. Você revisa e aprova antes do agendamento e da publicação no Instagram.'],
 ['É para quem está começando?','O foco inicial são criadores de SaaS, microsaas e infoapps que já têm um produto para divulgar. Ter uma página que explique sua oferta ajuda a dar contexto para a criação do conteúdo.'],
 ['Vai publicar sem a minha aprovação?','Não. A revisão e a aprovação fazem parte do fluxo planejado. Você decide o que pode ser agendado antes de qualquer publicação.'],
 ['Vai funcionar em outras redes?','O primeiro foco é o Instagram. Vídeos e publicação em outras redes não fazem parte do escopo inicial. A integração de publicação será validada antes da abertura.'],
 ['Quanto vai custar?','O preço ainda não foi definido. Entrar na lista é gratuito, não pede cartão e não cria uma assinatura.'],
];
function Cta({small=false}:{small?:boolean}){return <Button asChild className={`cta ${small?'small':''}`}><a href="#acesso">{small?'Entrar na lista':'Quero acesso antecipado'}<ArrowUpRight aria-hidden="true"/></a></Button>}
export default function Home(){
 const [active,setActive]=useState(0),[email,setEmail]=useState(''),[status,setStatus]=useState('idle'),[message,setMessage]=useState('');const item=examples[active];
 async function join(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('loading');setMessage('');const form=new FormData(e.currentTarget);try{const r=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,website:form.get('website')||''})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error||'Não foi possível registrar agora. Tente novamente.');setStatus('success');setMessage('Seu interesse foi registrado. Você está na lista de acesso antecipado.')}catch(err){setStatus('error');setMessage(err instanceof Error?err.message:'Não foi possível conectar. Tente novamente.')}}
 return <>
 <a className="skip" href="#conteudo">Pular para o conteúdo</a>
 <div className="blue-stage"><header className="shell nav"><a href="#" className="brand" aria-label="Launchwing — início"><img src="/brand/logo-inverse.svg" alt="Launchwing" width="568" height="128"/></a><nav aria-label="Navegação principal"><a href="#como-funciona">Como funciona</a><a href="#exemplos">O que você recebe</a><a href="#duvidas">Dúvidas</a></nav><Cta small/></header>
 <main id="conteudo"><section className="shell hero"><div className="hero-copy"><p className="eyebrow">↗ &nbsp; PARA QUEM CONSTRÓI PRODUTOS</p><h1>Seu produto<br/>merece<br/><span>aparecer.</span></h1><p className="hero-description">Você cuida do produto. A Launchwing está chegando para criar seu conteúdo e colocar sua divulgação em movimento.</p><Cta/><p className="micro">Em preparação. Entre na lista para saber quando abrir.</p></div><div className="hero-output"><div className="output-caption"><span>DO SEU PRODUTO</span><ArrowRight aria-hidden="true"/><span>PARA O MUNDO</span></div><div className="poster-stack"><div className="back-sheet sheet-one" aria-hidden="true">Ideia boa<br/>merece<br/>alcance.</div><div className="back-sheet sheet-two" aria-hidden="true">Seu próximo<br/>conteúdo<br/>começa aqui.</div><img className="hero-poster" src="/brand/post-lift.png" alt="Post ilustrativo: Você criou. Agora mostre. Seu produto merece aparecer." width="1080" height="1350" fetchPriority="high"/><div className="review-stamp"><Check size={18} aria-hidden="true"/><span>Você aprova.<br/><strong>A Launchwing publica.</strong></span></div></div><p className="sample-note">Peça ilustrativa da marca. Produto em preparação.</p></div></section><div className="shell promise-strip"><span>Um link como ponto de partida.</span><Plus aria-hidden="true"/><span>7 carrosséis com legenda.</span><Plus aria-hidden="true"/><span>Sua aprovação antes de publicar.</span></div></main></div>
 <section className="shell problem spaced"><p className="eyebrow">CONSTRUIR JÁ DÁ TRABALHO</p><div className="problem-grid"><h2>Divulgar não precisa<br/>começar do zero.<br/><span>Toda. Semana.</span></h2><div><p>Você termina uma funcionalidade. Corrige um bug. Responde um cliente. E o post que ia apresentar seu produto continua para depois.</p><p>A Launchwing está sendo criada para assumir essa rotina: transformar o que você construiu em conteúdo pronto para revisar e colocar no ar.</p></div></div></section>
 <section id="como-funciona" className="shell spaced"><div className="section-heading"><p className="eyebrow">COMO VAI FUNCIONAR</p><h2>Do link à publicação.<br/>Com você no controle.</h2></div><div className="steps"><article><span className="step-number">01</span><h3>Mostre seu produto.</h3><p>O link da sua página é o ponto de partida para entender o que você vende e para quem.</p><div className="url-example">↗ &nbsp; seuproduto.com.br</div></article><article><span className="step-number">02</span><h3>Receba o conteúdo.</h3><p>Sete carrosséis com legenda e chamada para ação, organizados para você revisar.</p><div className="tags"><span>Design</span><span>Legenda</span><span>CTA</span></div></article><article><span className="step-number">03</span><h3>Aprove. Deixe seguir.</h3><p>Depois da sua aprovação, o conteúdo segue para agendamento e publicação no Instagram.</p><div className="approved"><Check size={18} aria-hidden="true"/>Publicar só depois de aprovar</div></article></div></section>
 <section id="exemplos" className="examples-section"><div className="shell"><div className="example-heading"><div><p className="eyebrow">O QUE VAI PARA O SEU FEED</p><h2>Seu produto.<br/>Mais de um jeito<br/>de contar a história.</h2></div><p>Apresentação, problema, funcionamento, convite. Uma semana de conteúdo pode explorar ângulos diferentes da mesma oferta.</p></div><div className="example-demo"><div className={`demo-cover ${item.tone}`} aria-label={`Exemplo ${active+1}: ${item.type}`}><div className="cover-top"><span>Launchwing</span><span>0{active+1} / 07</span></div><h3>{item.title}</h3><p>{item.copy}</p><img src={`/brand/symbol-${item.tone==='blue'||item.tone==='ink'?'citron':'blue'}.svg`} alt="" width="96" height="96" loading="lazy"/></div><div className="example-details"><p className="eyebrow">EXEMPLO DE CAPA + LEGENDA</p><h3>{item.type}</h3><p className="caption-copy" aria-live="polite">{item.caption}</p><p className="demo-disclaimer">Exemplos editoriais feitos para apresentar a Launchwing. Não são resultados gerados pelo produto.</p><div className="example-controls"><Button variant="outline" size="icon" aria-label="Exemplo anterior" onClick={()=>setActive((active+6)%7)}><ChevronLeft/></Button><span aria-live="polite">{active+1} de 7</span><Button variant="outline" size="icon" aria-label="Próximo exemplo" onClick={()=>setActive((active+1)%7)}><ChevronRight/></Button></div></div></div></div></section>
 <section id="duvidas" className="shell faq-section spaced"><div><p className="eyebrow">ANTES DE ENTRAR</p><h2>Bom saber.</h2><p>Uma primeira versão com foco.<br/>E expectativas claras desde o início.</p></div><Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
 <section id="acesso" className="join-section"><div className="shell join-grid"><div><p className="eyebrow">PRÓXIMO PASSO: APARECER</p><h2>Você construiu.<br/><span>Vamos mostrar.</span></h2><p>Entre na lista para receber o aviso<br/>de abertura da Launchwing.</p></div><div className="join-form-box">{status==='success'?<div className="success-state" role="status"><Check size={32}/><h3>Você está na lista.</h3><p>{message}</p><p>Não houve cobrança nem criação de assinatura.</p></div>:<form onSubmit={join}><label htmlFor="email">Seu melhor e-mail</label><Input id="email" name="email" type="email" placeholder="voce@exemplo.com" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} aria-describedby="form-note form-status" aria-invalid={status==='error'}/><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><Button className="cta form-cta" type="submit" disabled={status==='loading'}>{status==='loading'?'Registrando…':'Quero acesso antecipado'}<ArrowUpRight aria-hidden="true"/></Button><p id="form-note">Ao entrar, você pede para receber um aviso por e-mail quando o acesso abrir. Entrar na lista é gratuito.</p><p id="form-status" role="status">{message}</p></form>}</div></div></section>
 <footer className="shell footer"><a href="#" aria-label="Launchwing — início"><img src="/brand/logo-primary.svg" alt="Launchwing" width="568" height="128"/></a><p>Seu produto merece aparecer.</p><span>© 2026 Launchwing</span></footer>
 </>;
}
